'use client';
import EmailLogin from './EmailLogin';
import {useEffect,useState} from 'react';
import {api} from './api';
import {Shell,PageHeading} from './Shell';
import {money} from '@/shared/models';
export function AccountLink(){const [user,setUser]=useState<any>(null);useEffect(()=>{api('customer/session').then(d=>setUser(d.customer)).catch(()=>{});},[]);return <a href="/account">{user?'My Account':'Sign in'}</a>}
export function AccountPrompt(){const [state,setState]=useState<any>(null);useEffect(()=>{api('customer/session').then(setState).catch(()=>{});},[]);return <p className="helper">{state?.customer?<>Signed in as {state.customer.name}. This request will appear in <a href="/account">My Account</a>.</>:<>You can continue as a guest. <a href="/account" target="_blank" rel="noreferrer">Sign in</a> before submitting to keep this request in your account. Refresh this page after signing in.</>}</p>}
export default function Account(){const [session,setSession]=useState<any>(null),[items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all');async function load(){const d=await api('customer/session');setSession(d);if(d.customer){if(new URLSearchParams(location.search).get('next')==='cart'){location.replace('/cart');return;}setItems((await api('customer/requests')).requests);}}useEffect(()=>{load().catch(e=>setError(e.message));const q=new URLSearchParams(location.search);if(q.has('error')){setError(q.get('error')==='unavailable'?'Google sign-in is not available yet. You can still browse, build an estimate or book a visit.':'Sign-in could not be completed. Please try again. Your cart is saved.');history.replaceState(null,'',q.get('next')==='cart'?'/account?next=cart':'/account');}},[]);async function logout(){setBusy(true);setError('');try{await api('customer/logout',{});location.assign('/account');}catch(e:any){setError(e.message);setBusy(false);}}
return <Shell><div className="cctv-compact-heading"><PageHeading label="FINCH CUSTOMER ACCOUNT" title={session?.customer?'Your Finch account':'Welcome to Finch'} description="Your orders, quotations and appointments in one place."/></div>{error&&<p className="error" role="alert">{error}</p>}{!session?<p>Loading account…</p>:!session.customer?<section className="panel account-signin"><EmailLogin emailEnabled={session.emailEnabled}/><div className="account-google"><p className="helper">Or use your Google account</p>{session.googleEnabled?<a className="button" href={typeof window!=='undefined'&&new URLSearchParams(location.search).get('next')==='cart'?'/api/customer/google?next=cart':'/api/customer/google'}>Continue with Google</a>:<p className="helper">Google sign-in is not yet connected.</p>}</div><div className="actions"><a className="textlink" href="/products">Continue browsing</a><a className="textlink" href="/estimate">Build an estimate</a><a className="textlink" href="/booking">Book a visit</a></div><p className="helper">By continuing, you acknowledge our <a href="/privacy">privacy notice</a>. Existing guest requests remain accessible using their private tracking links.</p></section>:<><section className="panel"><div className="section-heading"><div><h2>{session.customer.name}</h2><p>{session.customer.email}</p></div><button disabled={busy} className="button dark" onClick={logout}>{busy?'Signing out…':'Sign out'}</button></div><p className="helper">Sign-out ends your Finch session on this browser. It does not sign you out of Google.</p></section><div className="commerce-tabs">{[['all','All requests'],['order','My Orders'],['quote','My Quotations'],['booking','My Appointments'],['enquiry','My Enquiries']].map(([k,t])=><button key={k} className={filter===k?'button yellow':'button'} onClick={()=>setFilter(k)}>{t}</button>)}</div><div className="admin-list">{items.filter(r=>filter==='all'||r.kind===filter).map(r=><article className="panel" key={r.id}><div className="section-heading"><div><strong>{r.reference}</strong><p>{r.kind==='quote'?'Quotation':r.kind==='booking'?'Appointment':r.kind==='order'?'Order':'Enquiry'} · {r.status.replaceAll('-',' ')}</p></div><a className="button yellow" href={r.kind==='quote'?`/quote?id=${r.id}`:`/track?id=${r.id}`}>View details</a></div>{r.kind==='quote'&&<p>{money(r.total)}</p>}{r.status==='confirmed'&&<p>{r.confirmedDate} · {r.confirmedTime}</p>}</article>)}{!items.some(r=>filter==='all'||r.kind===filter)&&<div className="panel"><h2>No requests here yet.</h2><p>Orders, estimates and bookings submitted while signed in will appear here.</p><a href="/products" className="textlink">Visit the Shop</a></div>}</div><p className="helper">Older guest requests are not automatically linked by phone number or email. Continue using their private tracking links.</p></>}</Shell>}
