'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Camera as Instagram,SquarePlay as Youtube,Music2,MessageCircle,Phone,Mail,MapPin} from 'lucide-react';
import {api} from './api';
import {type Settings,defaultSettings,socialFields} from '@/shared/models';
const icons={tiktok:Music2,youtube:Youtube,instagram:Instagram};
export default function Footer(){
 const [settings,setSettings]=useState<Settings>(defaultSettings);
 useEffect(()=>{let active=true;api('settings').then(data=>{if(active)setSettings({...defaultSettings,...data});}).catch(()=>{});return()=>{active=false;};},[]);
 const whatsapp=`https://wa.me/${settings.phone.replace(/\D/g,'')}`;
 return <footer className="site-footer"><div className="footer-accent"/><div className="wrap"><div className="footer-invitation"><div><span className="eyebrow">LET’S BUILD SOMETHING RELIABLE</span><h2>A safer space. A better connection.</h2></div><a className="button yellow" href="/estimate">Plan your project <ArrowUpRight size={20}/></a></div><div className="footer-columns"><div className="footer-about"><a className="footer-wordmark" href="/">Finch<span>NETWORKS LTD.</span></a><p>Security, connectivity and automation.<br/>Thoughtfully installed. Ready for everyday life.</p><div className="footer-socials" aria-label="Finch social media">{settings.phone&&<a className="social-icon whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Chat with Finch on WhatsApp" title="WhatsApp"><MessageCircle size={21}/></a>}{socialFields.map(({key,label})=>{const Icon=key==='x'?null:icons[key];const content=Icon?<Icon size={21}/>:<span className="x-mark">𝕏</span>;return settings[key]?<a className={`social-icon ${key}`} key={key} href={settings[key]} target="_blank" rel="noreferrer" aria-label={`Finch on ${label}`} title={label}>{content}</a>:<span className={`social-icon inactive ${key}`} key={key} aria-label={`${label} profile link coming soon`} title={`${label} — profile link coming soon`}>{content}</span>;})}</div><small>Secure. Connect. Empower.</small></div><nav className="footer-links" aria-label="Footer services"><h3>Our expertise</h3><a href="/services/cctv">CCTV & repairs</a><a href="/estimate?item=service-1">Electric fences</a><a href="/estimate?item=service-2">Automatic gates</a><a href="/estimate?item=service-3">Office networking</a><a href="/estimate?item=service-4">Starlink installation</a><a href="/services/access-control">Access Control &amp; Intercoms</a></nav><nav className="footer-links" aria-label="Footer navigation"><h3>Explore Finch</h3><a href="/projects">Completed projects</a><a href="/products">Browse products</a><a href="/estimate">Build an estimate</a><a href="/contact">Repairs & support</a><a href="/privacy">Privacy notice</a></nav><div className="footer-contact"><h3>Let’s talk</h3>{settings.phone&&<a href={`tel:${settings.phone}`}><Phone size={18}/><span>{settings.phone}</span></a>}{settings.email&&<a href={`mailto:${settings.email}`}><Mail size={18}/><span>{settings.email}</span></a>}{settings.area&&<p><MapPin size={18}/><span>{settings.area}</span></p>}{settings.phone&&<a className="footer-whatsapp" href={whatsapp} target="_blank" rel="noreferrer">Start a WhatsApp chat <ArrowUpRight size={18}/></a>}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Finch Networks Ltd. All rights reserved.</span><span>A Finch Holdings company</span><a href="/admin">Staff sign-in <ArrowUpRight size={14}/></a></div></div></footer>;
}
