'use client';
import {useEffect,useState} from 'react';
import {ArrowRight} from 'lucide-react';
import {Shell,PageHeading} from './Shell';
import {planDefinitions,validatePlan,planSummary,type PlanKey,type ServicePlan} from '@/shared/service-plans';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export default function ServicePlanner({service}:{service:PlanKey}){const d=planDefinitions[service];const [answers,setAnswers]=useState<Record<string,string>>(()=>Object.fromEntries(d.fields.map(f=>[f.key,f.options?f.options[0]:''])));const [notes,setNotes]=useState('');const [error,setError]=useState('');
useEffect(()=>{const raw=new URLSearchParams(location.search).get('plan');if(raw){try{const p=validatePlan(JSON.parse(raw));if(p.service!==service)throw new Error();setAnswers(p.answers);setNotes(p.notes);}catch{setError('Please check your planning details.');}}},[service]);
function submit(e:React.FormEvent){e.preventDefault();try{const p=validatePlan({service,answers,notes});location.assign(`/estimate?plan=${encodeURIComponent(JSON.stringify(p))}`);}catch(e:any){setError(e.message);}}
return <Shell><div className="cctv-compact-heading"><PageHeading label="SERVICE PLANNING" title={d.title} description={d.description}/></div><div className="estimate-grid"><form className="panel form" onSubmit={submit}><div className="service-card-heading"><h2>Your project details</h2><span className="service-thumb service-card-thumb" aria-hidden="true" style={{backgroundPosition:`${d.index*25}% center`}}/></div>{d.fields.map(f=><label key={f.key}>{f.label}{f.options?<Select value={answers[f.key]} onValueChange={v=>{if(v)setAnswers(a=>({...a,[f.key]:v}));}}><SelectTrigger className="field-select" aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent>{f.options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>:<input type="number" min={0} max={f.max} step={f.unit==='metres'?'0.1':'1'} value={answers[f.key]} placeholder={`Leave blank if unsure (${f.unit})`} onChange={e=>setAnswers(a=>({...a,[f.key]:e.target.value}))}/>}</label>)}<label>Anything else we should know?<textarea rows={4} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Site conditions, existing equipment or your preferences"/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="button yellow">Continue to estimate request <ArrowRight size={18}/></button></form><aside className="panel estimate-summary"><div className="eyebrow">YOUR PLAN</div><h2>A starting point for Finch.</h2><p className="preserve">{planSummary({service,answers,notes})}</p><p className="notice">Equipment quantities and prices for this service will be confirmed after Finch reviews your requirements. This planning form does not calculate a final installation price.</p><a href="/estimate" className="textlink">Choose another service <ArrowRight size={18}/></a></aside></div></Shell>}
