import {currentCustomer} from './customer-auth';
import {initiateMpesa,stkPushReady} from './mpesa';
import {database} from './database';
import {products} from './catalog';
import {calculate} from './pricing';
import {isAdmin} from './auth';
import {defaultOffers,defaultCommerceSettings,salesStatuses} from '@/shared/commerce';
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'no-store'}});
const text=(v:unknown,max=3000)=>{if(typeof v!=='string'||v.length>max)throw Error('Check your text fields.');return v.trim();};
const amount=(v:unknown)=>{const n=Number(v);if(v===''||v===null||!Number.isFinite(n)||n<0||n>100000000)throw Error('Enter a valid amount.');return Math.round(n*100)/100;};
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const uuid=(v:unknown)=>{if(typeof v!=='string'||! /^[a-f0-9-]{36}$/.test(v))throw Error('Invalid reference.');return v;};
export async function record(id:string){const row=await database().prepare('SELECT * FROM commerce WHERE id=?').bind(id).first<any>();if(!row)throw Error('Record not found.');return {...JSON.parse(row.data),id:row.id,kind:row.kind,status:row.status,revision:row.revision,createdAt:row.created_at};}
async function save(r:any,oldRevision?:number){const {kind,status,revision,createdAt,...data}=r;if(oldRevision!==undefined){const q=await database().prepare('UPDATE commerce SET data=?,status=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(data),status,r.id,oldRevision).run();if(!q.meta.changes)throw Error('This record changed. Refresh and try again.');}else await database().prepare('INSERT INTO commerce (id,kind,data,status,created_at,rate_key,customer_id) VALUES (?,?,?,?,?,?,?)').bind(r.id,kind,JSON.stringify(data),status,createdAt||Date.now(),r.rateKey||'',r.customerId||null).run();if(r.kind==='quote'&&r.sourceId&&['quoted','accepted','deposit-paid','paid','installed','completed'].includes(r.status)){await database().batch([database().prepare("UPDATE commerce SET status=?,revision=revision+1 WHERE id=? AND kind='order'").bind(r.status,r.sourceId),database().prepare('UPDATE enquiries SET status=? WHERE id=?').bind(r.status,r.sourceId)]);}return record(r.id);}
export async function offers(){const rows=await database().prepare("SELECT data FROM commerce WHERE kind='offer'").all<any>();const m=new Map(defaultOffers.map(o=>[o.id,o]));rows.results.forEach(r=>{const o=JSON.parse(r.data);m.set(o.id,o);});return [...m.values()];}
export async function commerceSettings(){const r=await database().prepare("SELECT data FROM settings WHERE id='commerce'").first<any>();return {...defaultCommerceSettings,...(r?JSON.parse(r.data):{})};}
async function rate(req:Request){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(req.headers.get('x-finch-client-ip')||'local'));const key=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');const n=await database().prepare('SELECT count(*) AS n FROM commerce WHERE rate_key=? AND created_at>?').bind(key,Date.now()-600000).first<any>();if(n.n>=8)throw Error('Please wait a few minutes before submitting again.');return key;}
function customer(b:any){const name=text(b.name,100),phone=text(b.phone,40),location=text(b.location,300);if(!name||!location||!/^\+?[\d ()-]{7,30}$/.test(phone)||b.consent!==true||b.website)throw Error('Enter your contact details and agree to be contacted.');return {name,phone,location,notes:text(b.notes||'')};}
function mpesaPhone(value:unknown){const digits=text(String(value??''),40).replace(/[^\d]/g,'');const phone=digits.startsWith('0')?'254'+digits.slice(1):digits.startsWith('254')?digits:digits?'254'+digits:'';if(!/^254[17]\d{8}$/.test(phone))throw Error('Use a Kenyan M-Pesa number, for example 0712345678.');return phone;}
function amountDue(status:string,quote:any){if(!quote||['paid','installed','completed','cancelled','new','quoted'].includes(status))return null;if(status==='deposit-paid'){const rest=Math.round((Number(quote.total)-(Number(quote.payment?.amount)||0))*100)/100;return rest>0?rest:null;}if(status==='accepted')return Number(quote.deposit)>0?Number(quote.deposit):Number(quote.total);return null;}
async function ownedOrder(req:Request,id:string){const account=await currentCustomer(req);if(!account)return {error:json({error:'Please sign in to view this order.'},401)};const row=await database().prepare("SELECT customer_id FROM commerce WHERE id=? AND kind='order'").bind(id).first<{customer_id:string}>();if(!row||row.customer_id!==account.id)return {error:json({error:'Order not found.'},404)};const order=await record(id);const quoteRow=await database().prepare("SELECT id,data,status,revision FROM commerce WHERE kind='quote' AND status!='draft' AND json_extract(data,'$.sourceId')=? ORDER BY created_at DESC LIMIT 1").bind(id).first<any>();const quote=quoteRow?{...JSON.parse(quoteRow.data),id:quoteRow.id,status:quoteRow.status,revision:quoteRow.revision}:null;return {account,order,quote};}
function publicOrder(order:any,quote:any){const due=amountDue(order.status,quote);return {id:order.id,reference:order.reference,status:order.status,name:order.name,phone:order.phone,location:order.location,notes:order.notes||'',fulfilment:order.fulfilment,installation:order.installation===true,lines:order.calculation?.lines||[],subtotal:order.calculation?.subtotal??0,customerMessage:order.customerMessage||'',quote:quote?{id:quote.id,reference:quote.reference,revision:quote.revision,status:quote.status,lines:quote.lines,total:quote.total,deposit:quote.deposit,terms:quote.terms,expires:quote.expires,payment:quote.payment||null}:null,amountDue:due,stkReady:stkPushReady(),stkSent:order.stk?.status==='sent'?{phone:order.stk.phone,amount:order.stk.amount}:null};}
export async function commerceHandle(req:Request):Promise<Response|null>{const path=new URL(req.url).pathname.replace('/api/','');if(!path.startsWith('commerce'))return null;const admin=path.startsWith('commerce/admin');if(admin&&!await isAdmin(req))return json({error:'Administrator access is required.'},403);
if(req.method==='GET'){
if(path==='commerce/public'){const reviews=await database().prepare("SELECT data FROM commerce WHERE kind='review' AND status='published' ORDER BY created_at DESC LIMIT 30").all<any>();return json({offers:(await offers()).filter(o=>o.published),reviews:reviews.results.map(r=>{const d=JSON.parse(r.data);return {id:d.id,name:d.name,service:d.service,rating:d.rating,review:d.review};}),settings:await commerceSettings(),paymentsEnabled:false});}
if(path==='commerce/admin'){const rows=await database().prepare("SELECT * FROM commerce WHERE kind IN ('order','booking','quote','review') ORDER BY created_at DESC LIMIT 500").all<any>();return json({records:rows.results.map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind,status:r.status,revision:r.revision,createdAt:r.created_at})),offers:await offers(),settings:await commerceSettings()});}
if(path.startsWith('commerce/tracking/')){const id=uuid(path.split('/').pop());const row=await database().prepare("SELECT kind,data,status FROM commerce WHERE id=? AND kind IN ('order','booking')").bind(id).first<any>();let r:any;if(row){r={...JSON.parse(row.data),kind:row.kind,status:row.status};}else{const e=await database().prepare('SELECT reference,status,data FROM enquiries WHERE id=?').bind(id).first<any>();if(!e)return json({error:'Tracking link not found.'},404);r={reference:e.reference,status:e.status,kind:'enquiry',customerMessage:JSON.parse(e.data).customerMessage||''};}return json({reference:r.reference||`BOOK-${id.slice(0,8).toUpperCase()}`,kind:r.kind,status:r.status,customerMessage:r.customerMessage||'',...(r.kind==='booking'?{requestedDate:r.date,requestedTime:r.time,...(r.status==='confirmed'?{confirmedDate:r.confirmedDate,confirmedTime:r.confirmedTime}:{})}:{})});}
if(path.startsWith('commerce/order/')){const owned=await ownedOrder(req,uuid(path.split('/').pop()));if(owned.error)return owned.error;return json(publicOrder(owned.order,owned.quote));}
if(path.startsWith('commerce/quote/')){const r=await record(uuid(path.split('/').pop()));if(r.kind!=='quote'||r.status==='draft')throw Error('Quotation not available.');return json({id:r.id,reference:r.reference,revision:r.revision,status:r.status,lines:r.lines,total:r.total,deposit:r.deposit,terms:r.terms,expires:r.expires,acceptedAt:r.acceptedAt,payment:r.payment||null});}
return json({error:'Not found'},404);}
if(req.method!=='POST')return json({error:'Not found'},404);if(Number(req.headers.get('content-length'))>50000)throw Error('Request too large.');const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Request origin not allowed'},403);const b=await req.json() as any;if(!b||typeof b!=='object'||Array.isArray(b))throw Error('Invalid request.');
if(path==='commerce/order'){const account=await currentCustomer(req);if(!account)return json({error:'Please sign in or create an account to check out.'},401);const c=customer(b);const rateKey=await rate(req);const id=uuid(b.id);const found=await database().prepare('SELECT id FROM commerce WHERE id=?').bind(id).first();if(found)return json({reference:`ORD-${id.slice(0,8).toUpperCase()}`,duplicate:true,id});if(!['delivery','collection'].includes(b.fulfilment))throw Error('Choose delivery or collection.');const catalog=await products();if(!Array.isArray(b.items)||!b.items.length||b.items.some((i:any)=>!catalog.some(p=>p.id===i.id&&p.featured&&p.stockStatus!=='out-of-stock')))throw Error('Choose available shop products.');const calculation=calculate(b.items,catalog);const r=await save({id,kind:'order',status:'new',customerId:account.id,...c,reference:`ORD-${id.slice(0,8).toUpperCase()}`,calculation,fulfilment:b.fulfilment,installation:b.installation===true,rateKey});return json({reference:r.reference,id:r.id},201);}
if(path==='commerce/booking'){const c=customer(b);const rateKey=await rate(req);const day=text(b.date,10);if(!validDate(day)||day<new Date().toISOString().slice(0,10)||day>new Date(Date.now()+366*86400000).toISOString().slice(0,10))throw Error('Choose a preferred date within the next year.');if(!['Morning','Afternoon','Any time'].includes(b.time))throw Error('Choose a time preference.');const offer=(await offers()).find(o=>o.id===b.offer&&o.published);if(b.offer&&!offer)throw Error('This package is unavailable. Choose another option.');const id=uuid(b.id);const found=await database().prepare('SELECT id FROM commerce WHERE id=?').bind(id).first();if(found)return json({reference:`BOOK-${id.slice(0,8).toUpperCase()}`,id});const r=await save({id,kind:'booking',status:'requested',customerId:(await currentCustomer(req))?.id||null,...c,service:text(b.service,150),date:day,time:b.time,offer:offer?.name||'',rateKey});return json({reference:`BOOK-${r.id.slice(0,8).toUpperCase()}`,id:r.id},201);}
if(path==='commerce/stk'){const owned=await ownedOrder(req,uuid(b.id));if(owned.error)return owned.error;const due=amountDue(owned.order.status,owned.quote);if(due==null||due<=0)throw Error('This order is not ready for payment.');if(!Number.isInteger(due))throw Error('Finch needs to confirm this amount before M-Pesa can request it.');if(!stkPushReady())return json({error:'M-Pesa STK push is not connected yet. Finch will not charge your phone until it is connected.'},503);const phone=mpesaPhone(b.phone||owned.order.phone);const started=await initiateMpesa(due,phone,owned.order.reference);await save({...owned.order,stk:{...started,amount:due,phone,status:'sent',startedAt:Date.now()}},owned.order.revision);return json({ok:true,message:'Check your phone for the M-Pesa prompt and enter your PIN.'});}
if(path==='commerce/accept'){const r=await record(uuid(b.id));if(r.kind!=='quote'||r.revision!==b.revision||r.status!=='quoted'||r.expires<new Date().toISOString().slice(0,10)||b.accept!==true)throw Error('This quotation has changed, expired or already been accepted. Refresh to review it.');const name=text(b.name,100);if(!name)throw Error('Enter your name to accept.');await save({...r,status:'accepted',acceptedBy:name,acceptedAt:Date.now()},r.revision);return json({ok:true});}
if(path==='commerce/admin/quote'){const id=b.id?uuid(b.id):crypto.randomUUID();const old=b.id?await record(id):null;if(old&&(!['draft','quoted'].includes(old.status)||old.kind!=='quote'))throw Error('Accepted quotations cannot be edited. Create a new quotation.');if(!Array.isArray(b.lines)||!b.lines.length||b.lines.length>40)throw Error('Add between 1 and 40 quotation lines.');const lines=b.lines.map((l:any)=>{const name=text(l.name,200);const quantity=Number(l.quantity);if(!name||!Number.isInteger(quantity)||quantity<1||quantity>100000)throw Error('Check quotation quantities.');const unitPrice=amount(l.unitPrice);return {name,quantity,unitPrice,total:Math.round(unitPrice*quantity*100)/100};});const total=Math.round(lines.reduce((n:number,l:any)=>n+l.total,0)*100)/100;if(total>100000000)throw Error('Quotation total too large.');const deposit=amount(b.deposit);if(deposit>total)throw Error('Deposit cannot exceed the total.');const expires=text(b.expires,10);if(!validDate(expires)||expires<new Date().toISOString().slice(0,10))throw Error('Choose a valid expiry date.');const sourceId=text(b.sourceId||'',100);if(old&&sourceId!==old.sourceId)throw Error('The quotation source cannot be changed.');if(sourceId){uuid(sourceId);const a=await database().prepare("SELECT id FROM commerce WHERE id=? AND kind IN ('order','booking') UNION ALL SELECT id FROM enquiries WHERE id=?").bind(sourceId,sourceId).first();if(!a)throw Error('Source request not found.');}const status=b.status==='quoted'?'quoted':'draft';if(!text(b.name,100)||!text(b.phone,40)||!text(b.terms,5000))throw Error('Enter the customer details and quotation terms.');const result=await save({id,kind:'quote',status,name:text(b.name,100),phone:text(b.phone,40),sourceId,reference:old?.reference||`QUO-${id.slice(0,8).toUpperCase()}`,lines,total,deposit,expires,terms:text(b.terms,5000)},old?b.revision:undefined);return json(result);}
if(path==='commerce/admin/status'){const r=await record(uuid(b.id));const allowed=r.kind==='booking'?['requested','confirmed','completed','cancelled']:r.kind==='review'?['draft','published']:salesStatuses;if(!['order','booking','quote','review'].includes(r.kind)||!allowed.includes(b.status)||r.kind==='quote'&&(b.status==='accepted'||['new','draft','quoted'].includes(b.status)))throw Error('Invalid status.');let payment=r.payment;if(['paid','deposit-paid'].includes(b.status)){const reference=text(b.paymentReference||'',100);if(!reference)throw Error('Enter a verified payment receipt reference.');const paidAmount=amount(b.paidAmount);if(paidAmount<=0)throw Error('Enter the verified payment amount.');if(r.kind==='quote'&&b.status==='paid'&&paidAmount<r.total)throw Error('Use deposit-paid until the full quotation amount is received.');payment={reference,amount:paidAmount,confirmedAt:Date.now(),method:'Manually verified by Finch'};}const confirmedDate=r.kind==='booking'?text(b.confirmedDate||r.date,10):undefined;if(confirmedDate&&!validDate(confirmedDate))throw Error('Choose a valid appointment date.');return json(await save({...r,status:b.status,...(payment?{payment}:{}),...(confirmedDate?{confirmedDate,confirmedTime:text(b.confirmedTime||r.time,100)}:{}),customerMessage:text(b.customerMessage??r.customerMessage??'',1500),internalNotes:text(b.internalNotes||'',3000)},b.revision));}
if(path==='commerce/admin/offer'){const old=(await offers()).find(o=>o.id===b.id);const id=old?.id||crypto.randomUUID();if(!['package','maintenance'].includes(b.kind))throw Error('Choose a type.');const route=text(b.route,200);if(!/^\/(services\/[a-z-]+|booking(?:\?offer=[a-z0-9-]+)?)$/.test(route))throw Error('Use a service planner or booking link.');const data={id,kind:b.kind,name:text(b.name,150),description:text(b.description,1000),includes:text(b.includes,2000),frequency:text(b.frequency,150),price:b.price===''||b.price===null?null:amount(b.price),route,published:b.published===true};if(!data.name||!data.includes)throw Error('Enter the name and inclusions.');await database().prepare("INSERT INTO commerce(id,kind,data,status,created_at) VALUES (?,'offer',?,'saved',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(id,JSON.stringify(data),Date.now()).run();return json(data);}
if(path==='commerce/admin/review'){if(b.permission!==true)throw Error('Confirm customer permission before publishing a review.');const id=b.id?uuid(b.id):crypto.randomUUID();const previous=await database().prepare('SELECT kind FROM commerce WHERE id=?').bind(id).first<any>();if(previous&&previous.kind!=='review')throw Error('Invalid review reference.');const rating=Number(b.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw Error('Choose a rating from 1 to 5.');const data={id,name:text(b.name,100),service:text(b.service,150),review:text(b.review,2000),rating,permission:true};if(!data.name||!data.review)throw Error('Enter the customer name and review.');await database().prepare("INSERT INTO commerce(id,kind,data,status,created_at) VALUES (?,'review',?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,status=excluded.status,revision=revision+1").bind(id,JSON.stringify(data),b.published?'published':'draft',Date.now()).run();return json(data);}
if(path==='commerce/admin/settings'){const data=Object.fromEntries(Object.keys(defaultCommerceSettings).map(k=>[k,text(b[k],5000)]));await database().prepare("INSERT INTO settings(id,data) VALUES ('commerce',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify(data)).run();return json(data);}
return json({error:'Not found'},404);
}
