import {random,hashToken,cookie,setCookie,currentCustomer} from './customer-session';
export {currentCustomer,hashToken} from './customer-session';
import {emailAuthHandle,emailReady} from './email-auth';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import {database,config} from './database';
const jwks=createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'));
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
function configured(){return !!config('GOOGLE_CLIENT_ID')&&!!config('GOOGLE_CLIENT_SECRET')&&!!config('GOOGLE_REDIRECT_URI');}
function redirect(req:Request,path:string,cookies:string[]=[]){const h=new Headers({'Location':path,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});cookies.forEach(c=>h.append('Set-Cookie',c));return new Response(null,{status:303,headers:h});}
export async function customerAuthHandle(req:Request):Promise<Response|null>{const url=new URL(req.url),path=url.pathname;if(!path.startsWith('/api/customer/'))return null;const emailResponse=await emailAuthHandle(req);if(emailResponse)return emailResponse;
if(path==='/api/customer/session'&&req.method==='GET')return json({customer:await currentCustomer(req),googleEnabled:configured(),emailEnabled:emailReady()});
if(path==='/api/customer/logout'&&req.method==='POST'){if(req.headers.get('origin')!==url.origin)return json({error:'Request origin not allowed.'},403);const token=cookie(req,'finch_customer');if(token)await database().prepare('DELETE FROM customer_sessions WHERE hash=?').bind(await hashToken(token)).run();const r=json({ok:true});r.headers.append('Set-Cookie',setCookie(req,'finch_customer','',0));return r;}
if(path==='/api/customer/google'&&req.method==='GET'){if(!configured())return redirect(req,'/account?error=unavailable'+(url.searchParams.get('next')==='cart'?'&next=cart':''));const callback=new URL(config('GOOGLE_REDIRECT_URI'));if(callback.origin!==url.origin||callback.pathname!=='/api/customer/callback'||(callback.protocol!=='https:'&&callback.hostname!=='localhost'))return redirect(req,'/account?error=configuration');const state=random(),nonce=random(),verifier=random();const challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');await database().batch([database().prepare('DELETE FROM oauth_flows WHERE expires_at<?').bind(Date.now()),database().prepare('DELETE FROM customer_sessions WHERE expires_at<?').bind(Date.now()),database().prepare('INSERT INTO oauth_flows(hash,nonce,verifier,expires_at) VALUES (?,?,?,?)').bind(await hashToken(state),nonce,verifier,Date.now()+600000)]);const target=new URL('https://accounts.google.com/o/oauth2/v2/auth');target.search=new URLSearchParams({client_id:config('GOOGLE_CLIENT_ID'),redirect_uri:callback.href,response_type:'code',scope:'openid email profile',state,nonce,code_challenge:challenge,code_challenge_method:'S256',prompt:'select_account'}).toString();return redirect(req,target.href,[setCookie(req,'finch_oauth',state,600),setCookie(req,'finch_return',url.searchParams.get('next')==='cart'?'cart':'account',600)]);}
if(path==='/api/customer/callback'&&req.method==='GET'){const clear=setCookie(req,'finch_oauth','',0);try{const state=url.searchParams.get('state');if(!configured()||!state||!/^[a-f0-9]{64}$/.test(state)||state!==cookie(req,'finch_oauth'))throw Error('Invalid OAuth state');const flow=await database().prepare('DELETE FROM oauth_flows WHERE hash=? AND expires_at>? RETURNING nonce,verifier').bind(await hashToken(state),Date.now()).first<any>();if(!flow||url.searchParams.has('error'))throw Error('Cancelled or expired');const code=url.searchParams.get('code');if(!code)throw Error('Missing code');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:config('GOOGLE_CLIENT_ID'),client_secret:config('GOOGLE_CLIENT_SECRET'),code,grant_type:'authorization_code',redirect_uri:config('GOOGLE_REDIRECT_URI'),code_verifier:flow.verifier}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Token exchange failed');const tokens=await r.json() as any;const {payload}=await jwtVerify(tokens.id_token,jwks,{issuer:['https://accounts.google.com','accounts.google.com'],audience:config('GOOGLE_CLIENT_ID'),algorithms:['RS256'],requiredClaims:['sub','exp','iat','nonce','email','email_verified']});if(payload.nonce!==flow.nonce||payload.email_verified!==true||typeof payload.email!=='string'||!payload.sub||(payload.azp&&payload.azp!==config('GOOGLE_CLIENT_ID')))throw Error('Identity validation failed');const id='google:'+payload.sub;const token=random();await database().batch([database().prepare('INSERT INTO customers(id,email,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name').bind(id,payload.email.slice(0,320),String(payload.name||payload.email).slice(0,160),Date.now()),database().prepare('DELETE FROM customer_sessions WHERE hash=?').bind(await hashToken(cookie(req,'finch_customer'))),database().prepare('INSERT INTO customer_sessions(hash,customer_id,expires_at) VALUES (?,?,?)').bind(await hashToken(token),id,Date.now()+7*86400000)]);return redirect(req,cookie(req,'finch_return')==='cart'?'/cart':'/account',[clear,setCookie(req,'finch_return','',0),setCookie(req,'finch_customer',token,7*86400)]);}catch{return redirect(req,'/account?error=signin'+(cookie(req,'finch_return')==='cart'?'&next=cart':''),[clear,setCookie(req,'finch_return','',0)]);}}
if(path==='/api/customer/requests'&&req.method==='GET'){const c=await currentCustomer(req);if(!c)return json({error:'Please sign in to view your account.'},401);const email=c.email.trim().toLowerCase();await database().prepare("UPDATE enquiries SET customer_id=? WHERE customer_id IS NULL AND lower(json_extract(data,'$.email'))=?").bind(c.id,email).run();await database().prepare("UPDATE commerce SET customer_id=? WHERE customer_id IS NULL AND lower(json_extract(data,'$.email'))=?").bind(c.id,email).run();await database().prepare("UPDATE commerce SET customer_id=? WHERE kind='quote' AND customer_id IS NULL AND (EXISTS (SELECT 1 FROM enquiries e WHERE e.id=json_extract(commerce.data,'$.sourceId') AND e.customer_id=?) OR EXISTS (SELECT 1 FROM commerce o WHERE o.id=json_extract(commerce.data,'$.sourceId') AND o.kind IN ('order','booking') AND o.customer_id=?))").bind(c.id,c.id,c.id).run();const commerce=await database().prepare("SELECT id,kind,data,status,created_at FROM commerce WHERE customer_id=? AND kind IN ('order','booking','quote') AND status!='draft' ORDER BY created_at DESC LIMIT 100").bind(c.id).all<any>();const enquiries=await database().prepare('SELECT id,reference,data,status,created_at FROM enquiries WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').bind(c.id).all<any>();const present=(row:any,kind:string,data:any)=>({id:row.id,kind,reference:data.reference||row.reference||`${kind==='booking'?'BOOK':'REQ'}-${row.id.slice(0,8).toUpperCase()}`,status:row.status,createdAt:row.created_at,name:data.name||'',phone:data.phone||'',location:data.location||'',email:data.email||'',notes:typeof data.notes==='string'?data.notes:'',project:data.project||'',summary:data.cctvSummary||data.planSummary||'',total:data.total??data.calculation?.subtotal??null,hasUnpriced:data.calculation?.hasUnpriced===true,expires:data.expires||'',fulfilment:data.fulfilment||'',service:data.service||data.offer||'',confirmedDate:data.confirmedDate||'',confirmedTime:data.confirmedTime||'',lines:(data.lines||data.calculation?.lines||[]).slice(0,8).map((l:any)=>({name:l.name,quantity:l.quantity,total:l.total??null}))});const requests=[...commerce.results.map(r=>present(r,r.kind,JSON.parse(r.data))),...enquiries.results.map(r=>present(r,'enquiry',JSON.parse(r.data)))];return json({requests:requests.sort((a,b)=>b.createdAt-a.createdAt)});}
return json({error:'Not found'},404);}
