import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFImage,type PDFPage} from 'pdf-lib';
import {defaultQuoteExclusions,defaultQuotePayment,receiptStatement} from '@/shared/commerce';

const teal=rgb(0.027,0.373,0.388);
const gold=rgb(0.965,0.808,0.184);
const ink=rgb(0.082,0.188,0.267);
const muted=rgb(0.204,0.345,0.396);
const rule=rgb(0.73,0.84,0.87);
const wash=rgb(0.945,0.98,0.973);
const white=rgb(1,1,1);
const pageWidth=595.28;
const pageHeight=841.89;
const left=40;
const right=555;
const width=right-left;

type Brand={phone:string;email:string;area:string};
type Item={name:string;quantity:number;unitPrice:number|null;total:number|null};
type Section={title:string;body:string;bullets?:boolean};
export type EstimatePdfInput={reference?:string;createdAt?:number;name?:string;phone?:string;location?:string;notes?:string;cctvSummary?:string;planSummary?:string;calculation:{lines:Item[];subtotal:number;hasUnpriced?:boolean;note?:string}};
export type QuotePdfInput={reference:string;createdAt?:number;name?:string;phone?:string;location?:string;project?:string;lines:Item[];total:number;deposit?:number;expires?:string;terms?:string;scope?:string;exclusions?:string;paymentDetails?:string};
export type ReceiptPdfInput={reference:string;name?:string;phone?:string;location?:string;project?:string;lines:Item[];total:number;payment:{reference:string;amount:number;confirmedAt?:number}};

function clean(value:unknown){return String(value??'').replace(/[\u2013\u2014]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/\u2022/g,'-').replace(/\u00a0/g,' ').replace(/[^\x0a\x20-\xff]/g,'').replace(/[ \t]+\n/g,'\n').trim();}
function kes(amount:number){const value=Math.round(amount*100)/100;const negative=value<0;const [whole,fraction]=Math.abs(value).toFixed(2).split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,',');return `${negative?'-':''}KES ${fraction==='00'?grouped:`${grouped}.${fraction}`}`;}
function ordinal(day:number){const teen=day%100;if(teen>=11&&teen<=13)return `${day}th`;return `${day}${['th','st','nd','rd'][day%10]||'th'}`;}
function longDate(value:number|string){const date=typeof value==='number'?new Date(value):new Date(`${String(value).slice(0,10)}T12:00:00Z`);const zone=typeof value==='number'?'Africa/Nairobi':'UTC';const parts=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:zone}).formatToParts(date);const day=Number(parts.find(part=>part.type==='day')?.value||'1');const month=parts.find(part=>part.type==='month')?.value||'';const year=parts.find(part=>part.type==='year')?.value||'';return `${ordinal(day)} ${month} ${year}`;}
function wrap(text:string,font:PDFFont,size:number,max:number){const blocks=clean(text).split('\n');const lines:string[]=[];const pieces=(word:string)=>{if(font.widthOfTextAtSize(word,size)<=max)return [word];const out:string[]=[];let part='';for(const char of word){const next=part+char;if(font.widthOfTextAtSize(next,size)<=max)part=next;else{if(part)out.push(part);part=char;}}if(part)out.push(part);return out;};for(const block of blocks){const words=block.split(/\s+/).filter(Boolean).flatMap(pieces);if(!words.length){lines.push('');continue;}let current='';for(const word of words){const next=current?`${current} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=max)current=next;else{if(current)lines.push(current);current=word;}}if(current)lines.push(current);}return lines.length?lines:[''];}

let logoCache:Promise<Uint8Array|null>|undefined;
function logoBytes(){logoCache??=readFile(join(process.cwd(),'public','finch-logo.png')).then(bytes=>new Uint8Array(bytes)).catch(()=>null);return logoCache;}

class Sheet{
pdf:PDFDocument;font:PDFFont;bold:PDFFont;logo:PDFImage|null;brand:Brand;
constructor(pdf:PDFDocument,font:PDFFont,bold:PDFFont,logo:PDFImage|null,brand:Brand){this.pdf=pdf;this.font=font;this.bold=bold;this.logo=logo;this.brand=brand;}
page!:PDFPage;
y=0;
private header(){const page=this.page;page.drawRectangle({x:0,y:pageHeight-78,width:pageWidth,height:78,color:teal});page.drawRectangle({x:0,y:pageHeight-84,width:pageWidth,height:6,color:gold});if(this.logo){page.drawRectangle({x:28,y:pageHeight-72,width:188,height:58,color:white});page.drawImage(this.logo,{x:32,y:pageHeight-69,width:180,height:52});}else page.drawText('FINCH NETWORKS LTD',{x:36,y:pageHeight-48,size:14,font:this.bold,color:gold});const lines=[this.brand.phone||'+254 707 625129',this.brand.email||'finchnetworkslimited@gmail.com',this.brand.area||'Kenya'];lines.forEach((line,index)=>{const size=10;const text=clean(line);page.drawText(text,{x:right-this.font.widthOfTextAtSize(text,size),y:pageHeight-36-index*14,size,font:this.font,color:white});});this.y=pageHeight-112;}
addPage(){this.page=this.pdf.addPage([pageWidth,pageHeight]);this.header();}
private gap(space:number){if(this.y-space<52)this.addPage();}
text(value:string,options:{size?:number;font?:PDFFont;color?:ReturnType<typeof rgb>;indent?:number;gap?:number;max?:number}={}){const size=options.size??10;const font=options.font??this.font;const color=options.color??ink;const indent=options.indent??0;const max=options.max??width-indent;const lines=wrap(value,font,size,max);const gap=options.gap??4;this.gap(lines.length*(size+3)+gap);for(const line of lines){this.page.drawText(line,{x:left+indent,y:this.y,size,font,color});this.y-=size+3;}this.y-=gap;return this;}
ruleLine(){this.gap(12);this.page.drawLine({start:{x:left,y:this.y},end:{x:right,y:this.y},thickness:0.6,color:rule});this.y-=14;}
heading(title:string){this.gap(28);this.page.drawRectangle({x:left,y:this.y-4,width:4,height:16,color:gold});this.page.drawText(clean(title),{x:left+12,y:this.y,size:12,font:this.bold,color:teal});this.y-=22;}
meta(rows:[string,string][]){const labelWidth=92;for(const [label,value] of rows){if(!clean(value))continue;const lines=wrap(value,this.font,10,width-labelWidth);this.gap(lines.length*13+6);this.page.drawText(clean(label).toUpperCase(),{x:left,y:this.y,size:8,font:this.bold,color:muted});lines.forEach((line,index)=>this.page.drawText(line,{x:left+labelWidth,y:this.y-index*13,size:10,font:this.font,color:ink}));this.y-=lines.length*13+6;}}
table(items:Item[],totalLabel:string,total:number|null){const columns=[28,247,46,92,102];const headers=['No','Item description','Qty','Unit price','Total'];const drawHeader=()=>{this.gap(26);this.page.drawRectangle({x:left,y:this.y-8,width,height:22,color:teal});let x=left;headers.forEach((header,index)=>{this.page.drawText(header,{x:x+4,y:this.y-1,size:8,font:this.bold,color:white});x+=columns[index];});this.y-=24;};drawHeader();items.forEach((item,index)=>{const name=wrap(item.name||'Item',this.font,9,columns[1]-10);const height=Math.max(22,name.length*12+8);if(this.y-height<52){this.addPage();drawHeader();}if(index%2===0)this.page.drawRectangle({x:left,y:this.y-height+14,width,height,color:wash});let x=left;const cells=[String(index+1),'',String(item.quantity),item.unitPrice==null?'To confirm':kes(item.unitPrice),item.total==null?'To confirm':kes(item.total)];cells.forEach((cell,cellIndex)=>{if(cellIndex!==1)this.page.drawText(cell,{x:x+4,y:this.y,size:9,font:cellIndex===0?this.bold:this.font,color:ink});x+=columns[cellIndex];});name.forEach((line,lineIndex)=>this.page.drawText(line,{x:left+columns[0]+4,y:this.y-lineIndex*12,size:9,font:this.font,color:ink}));this.y-=height;});this.gap(32);this.page.drawRectangle({x:left,y:this.y-8,width,height:26,color:rgb(1,0.98,0.9)});this.page.drawText(totalLabel,{x:left+8,y:this.y,size:10,font:this.bold,color:ink});const amount=total==null?'To confirm':kes(total);this.page.drawText(amount,{x:right-8-this.bold.widthOfTextAtSize(amount,11),y:this.y,size:11,font:this.bold,color:teal});this.y-=28;}
sections(blocks:Section[]){for(const block of blocks){const body=clean(block.body);if(!body)continue;this.heading(block.title);for(const paragraph of body.split('\n').map(line=>line.trim()).filter(Boolean))this.text(block.bullets&&!paragraph.startsWith('-')?`- ${paragraph}`:paragraph,{size:10,gap:2});this.y-=6;}}
finish(){const pages=this.pdf.getPages();pages.forEach((page,index)=>{page.drawRectangle({x:0,y:0,width:pageWidth,height:8,color:gold});const label=clean(`Finch Networks Ltd  ·  Secure. Connect. Empower.  ·  Page ${index+1} of ${pages.length}`);page.drawText(label,{x:left,y:24,size:8,font:this.font,color:muted});});}
async save(){this.finish();return this.pdf.save();}
}

async function open(brand:Brand){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const bytes=await logoBytes();const logo=bytes?await pdf.embedPng(bytes):null;pdf.setTitle('Finch Networks Ltd');pdf.setAuthor('Finch Networks Ltd');pdf.setCreator('Finch Networks Ltd');return new Sheet(pdf,font,bold,logo,brand);}

function brandOf(settings?:Partial<Brand>):Brand{return {phone:clean(settings?.phone)||'+254 707 625129',email:clean(settings?.email)||'finchnetworkslimited@gmail.com',area:clean(settings?.area)||'Kenya'};}

export async function createEstimatePdf(data:EstimatePdfInput,settings?:Partial<Brand>){const sheet=await open(brandOf(settings));sheet.addPage();sheet.text('ESTIMATE',{size:18,font:sheet.bold,color:teal,gap:2});sheet.text('Not a final quotation. Finch confirms delivery, installation and the total before you pay.',{size:9,color:muted,gap:10});sheet.meta([['Reference',data.reference||'Not yet submitted'],['Date',longDate(data.createdAt||Date.now())],['Client',data.name||'Customer'],['Phone',data.phone||''],['Location',data.location||'']]);sheet.ruleLine();if(data.cctvSummary)sheet.text(data.cctvSummary,{gap:8});if(data.planSummary)sheet.text(data.planSummary,{gap:8});sheet.table(data.calculation.lines,data.calculation.hasUnpriced?'Priced items subtotal':'Estimate subtotal',data.calculation.subtotal);const notes=[data.calculation.note||'Prices, installation and site requirements will be confirmed by Finch.',data.calculation.hasUnpriced?'Some items still need a price. This is not a final total.':'',data.notes?`Project details: ${data.notes}`:''].filter(Boolean);sheet.sections([{title:'Before this becomes a quotation',body:notes.join('\n')}]);return sheet.save();}

export async function createQuotationPdf(quote:QuotePdfInput,settings?:Partial<Brand>){const brand=brandOf(settings);const sheet=await open(brand);const project=clean(quote.project);const date=longDate(quote.createdAt||Date.now());const deposit=Number(quote.deposit)||0;const balance=Math.round((Number(quote.total)-deposit)*100)/100;if(project){sheet.addPage();sheet.text('PROPOSAL',{size:11,font:sheet.bold,color:muted,gap:2});sheet.text(project,{size:16,font:sheet.bold,color:ink,gap:16});sheet.meta([['Client',quote.name||'Customer'],['Project',project],['Prepared by','Finch Networks Ltd'],['Phone',brand.phone],['Email',brand.email],['Address',brand.area],['Date',date],['Reference',quote.reference]]);}
sheet.addPage();sheet.text('QUOTATION',{size:18,font:sheet.bold,color:teal,gap:2});sheet.text('Finch Networks Ltd  ·  Secure. Connect. Empower.',{size:9,color:muted,gap:10});sheet.meta([['Quotation no',quote.reference],['Date',date],['Valid until',quote.expires?longDate(quote.expires):''],['Client',quote.name||'Customer'],['Phone',quote.phone||''],['Location',quote.location||''],['Project',project]]);sheet.ruleLine();sheet.table(quote.lines,'TOTAL',quote.total);if(deposit>0)sheet.text(`Payment terms: ${kes(deposit)} deposit on acceptance. Balance of ${kes(balance)} on completion, testing and commissioning.`,{size:10,gap:8});
const sections:Section[]=[{title:'Terms',body:quote.terms||''},{title:'Payment',body:quote.paymentDetails||defaultQuotePayment},{title:'Scope of work',body:quote.scope||'',bullets:true},{title:'Exclusions',body:quote.exclusions||defaultQuoteExclusions,bullets:true},{title:'Important notes',body:['Equipment supplied is subject to availability. Any substitution has equal or better specifications and needs your approval.','The customer provides suitable mounting surfaces, reliable power and access to the work areas. Extra work found on site is quoted separately.','The work is complete after installation, testing, commissioning and your confirmation.','Accepting this quotation approves the listed scope, prices and payment terms. Any change is agreed in writing.'].join('\n'),bullets:true},{title:'Thank you',body:'Thank you for trusting Finch Networks Ltd. We value the opportunity to serve you and remain committed to a reliable, professional installation.'}];
sheet.sections(sections);return sheet.save();}

export async function createReceiptPdf(quote:ReceiptPdfInput,settings?:Partial<Brand>){const brand=brandOf(settings);const sheet=await open(brand);const received=Math.round((Number(quote.payment.amount)||0)*100)/100;const total=Math.round((Number(quote.total)||0)*100)/100;const balance=Math.round((total-received)*100)/100;sheet.pdf.setTitle(`Receipt ${quote.reference}`);sheet.pdf.setSubject('Payment receipt from Finch Networks Ltd');sheet.addPage();sheet.text('RECEIPT',{size:18,font:sheet.bold,color:teal,gap:2});sheet.text('Finch Networks Ltd  ·  Secure. Connect. Empower.',{size:9,color:muted,gap:10});sheet.meta([['Receipt for',quote.reference],['Date',longDate(quote.payment.confirmedAt||Date.now())],['Received from',quote.name||'Customer'],['Phone',quote.phone||''],['Location',quote.location||''],['Project',quote.project||''],['Payment reference',quote.payment.reference]]);sheet.ruleLine();sheet.table(quote.lines,'QUOTATION TOTAL',total);sheet.text(`Amount received by Finch Networks Ltd: ${kes(received)}`,{size:12,font:sheet.bold,color:teal,gap:6});sheet.text(balance>0?`Balance remaining: ${kes(balance)}. Due on completion, testing and commissioning.`:'Paid in full.',{size:10,gap:8});sheet.sections([{title:'Payment',body:receiptStatement},{title:'Thank you',body:'Thank you for trusting Finch Networks Ltd.'}]);return sheet.save();}

export function pdfResponse(bytes:Uint8Array,filename:string){const safe=filename.replace(/[\\/]/g,'-').replace(/[^A-Za-z0-9._-]/g,'')||'Finch-document.pdf';return new Response(Buffer.from(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${safe}"`,'Cache-Control':'private, no-store'}});}
