import {customerAuthHandle,currentCustomer} from './customer-auth';
import {commerceHandle} from './commerce';
import {validatePlan,planSummary,planDefinitions} from '@/shared/service-plans';
import {buildCctv} from './cctv';
import {database,media} from './database';
import {products,projects,settings} from './catalog';
import {calculate} from './pricing';
import {isAdmin} from './auth';
import {createEstimatePdf,pdfResponse} from './pdf';
import {categories} from '@/shared/models';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const previewHits=new Map<string,number[]>();
function str(v:unknown,max=5000){if(typeof v!=='string'||v.length>max)throw new Error('Please check the text fields.');return v.trim();}
function imagePath(v:unknown){const p=str(v,200);if(p&&p!=='/solar-cctv.webp'&&!/^\/api\/media\/[a-f0-9-]+\.(png|jpg|webp)$/.test(p))throw new Error('Upload an image first.');return p;}
export async function handle(req:Request):Promise<Response>{try{
const customerResponse=await customerAuthHandle(req);if(customerResponse)return customerResponse;
const commerceResponse=await commerceHandle(req);if(commerceResponse)return commerceResponse;
const path=new URL(req.url).pathname.replace('/api/','');
if(req.method==='POST'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Request origin not allowed.'},403);}
if(path.startsWith('media/')&&req.method==='GET'){const key=path.slice(6);if(!/^[a-f0-9-]+\.(png|jpg|webp)$/.test(key))return json({error:'Not found'},404);const object=await media().get(key);if(!object)return json({error:'Not found'},404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}});}
if(path==='settings'&&req.method==='GET')return json(await settings());
if(path==='catalog'&&req.method==='GET')return json({products:await products(),projects:await projects(),settings:await settings()});
if(path.startsWith('estimate/')&&req.method==='GET'&&path!=='estimate/preview'){const id=path.slice(9);if(!/^[a-f0-9-]{36}$/.test(id))return json({error:'Not found'},404);const row=await database().prepare('SELECT data FROM enquiries WHERE id=?').bind(id).first<{data:string}>();if(!row)return json({error:'Not found'},404);const data=JSON.parse(row.data);return pdfResponse(await createEstimatePdf(data,await settings()),`Finch-${data.reference||'estimate'}.pdf`);}
if(path.startsWith('admin')){if(!await isAdmin(req))return json({error:'Administrator access is required.'},403);
if(path==='admin'&&req.method==='GET'){const rows=await database().prepare('SELECT id,reference,data,status,created_at FROM enquiries ORDER BY created_at DESC LIMIT 200').all();return json({products:await products(true),projects:await projects(true),settings:await settings(),enquiries:rows.results.map((r:any)=>({...JSON.parse(r.data),status:r.status}))});}
if(path==='admin/upload'&&req.method==='POST'){if(Number(req.headers.get('content-length'))>8_500_000)throw new Error('Use an image smaller than 8 MB.');const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>8_000_000||file.size===0)throw new Error('Choose an image up to 8 MB.');const buffer=await file.arrayBuffer();const b=new Uint8Array(buffer);const jpg=b[0]===255&&b[1]===216&&b[2]===255;const png=b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71;const webp=String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP';if(!jpg&&!png&&!webp)throw new Error('Upload a JPG, PNG or WebP image.');const ext=jpg?'jpg':png?'png':'webp';const key=`${crypto.randomUUID()}.${ext}`;await media().put(key,buffer,{httpMetadata:{contentType:`image/${jpg?'jpeg':ext}`}});return json({url:`/api/media/${key}`});}
}
if(req.method!=='POST')return json({error:'Not found'},404);
if(Number(req.headers.get('content-length'))>100000)return json({error:'Request too large'},413);
const body=await req.json() as Record<string,any>; if(!body||typeof body!=='object'||Array.isArray(body))throw new Error('Invalid request.');
if(path==='estimate/preview'){const clip=(v:unknown,max:number)=>typeof v==='string'?v.trim().slice(0,max):'';const now=Date.now();const ip=req.headers.get('x-finch-client-ip')||'local';const hits=(previewHits.get(ip)||[]).filter(t=>now-t<600000);if(hits.length>=20)return json({error:'Please wait a few minutes before downloading another estimate.'},429);hits.push(now);previewHits.set(ip,hits);const plan=body.plan?validatePlan(body.plan):null;const catalog=await products();const cctv=body.cctv?buildCctv(body.cctv,catalog):null;const calculation=cctv?cctv.calculation:calculate(plan?[{id:`service-${planDefinitions[plan.service].index}`,quantity:1}]:body.items,catalog);if(!calculation.lines.length)throw new Error('Add an item before downloading an estimate.');return pdfResponse(await createEstimatePdf({name:clip(body.name,100),phone:clip(body.phone,40),location:clip(body.location,200),notes:clip(body.notes,3000),calculation,...(cctv?{cctvSummary:cctv.summary}:{}),...(plan?{planSummary:planSummary(plan)}:{}),createdAt:now},await settings()),'Finch-estimate.pdf');}
if(path==='plan'){const plan=validatePlan(body.plan);const calculation=calculate([{id:`service-${planDefinitions[plan.service].index}`,quantity:1}],await products());return json({plan,summary:planSummary(plan),calculation});}
if(path==='cctv')return json(buildCctv(body.config,await products()));
if(path==='calculate')return json(calculate(body.items,await products()));
if(path==='enquiries'){
if(body.website)return json({error:'Unable to submit this request.'},400);if(body.consent!==true)throw new Error('Please agree to be contacted about this request.');
const name=str(body.name,100),phone=str(body.phone,40),location=str(body.location,200),notes=str(body.notes||'',3000);if(!name||!location||!/^\+?[\d ()-]{7,30}$/.test(phone))throw new Error('Enter your name, phone number and location.');if(body.cctv&&body.plan)throw new Error('Submit one service plan at a time.');const plan=body.plan?validatePlan(body.plan):null;const catalog=await products();const cctv=body.cctv?buildCctv(body.cctv,catalog):null;const calculation=cctv?cctv.calculation:calculate(plan?[{id:`service-${planDefinitions[plan.service].index}`,quantity:1}]:body.items,catalog);if(!calculation.lines.length&&!notes)throw new Error('Choose an item or describe your request.');
const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(req.headers.get('x-finch-client-ip')||'local'));const rateKey=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');const recent=await database().prepare('SELECT count(*) AS n FROM enquiries WHERE rate_key=? AND created_at>?').bind(rateKey,Date.now()-600000).first<{n:number}>();if((recent?.n||0)>=5)return json({error:'Please wait a few minutes before sending another request.'},429);
const id=crypto.randomUUID();const reference=`FN-${id.slice(0,8).toUpperCase()}`;const data={id,reference,name,phone,location,notes,calculation,...(cctv?{cctv:cctv.config,cctvSummary:cctv.summary}:{}),...(plan?{plan,planSummary:planSummary(plan)}:{}),createdAt:Date.now()};await database().prepare('INSERT INTO enquiries (id,reference,data,status,created_at,rate_key,customer_id) VALUES (?,?,?,?,?,?,?)').bind(id,reference,JSON.stringify(data),'new',data.createdAt,rateKey,(await currentCustomer(req))?.id||null).run();return json({id,reference,calculation,settings:await settings()},201);
}
if(path==='admin/products'){const id=str(body.id||crypto.randomUUID(),100);const name=str(body.name,160);if(!name)throw new Error('Enter a product name.');const price=body.price===null||body.price===''?null:Number(body.price);if(price!==null&&(!Number.isFinite(price)||price<0||price>100000000))throw new Error('Enter a valid price.');const category=str(body.category,100);if(!categories.includes(category))throw new Error('Choose a service category.');const existingProduct=(await products(true)).find(p=>p.id===id);const data={id,name,category,stockStatus:['in-stock','out-of-stock','on-request'].includes(body.stockStatus)?body.stockStatus:(existingProduct?.stockStatus||'on-request'),featured:body.featured===undefined?(existingProduct?.featured??false):body.featured===true,description:str(body.description),price:price===null?null:Math.round(price*100)/100,image:imagePath(body.image||''),published:body.published===true,unit:str(body.unit||'item',30),availability:str(body.availability||'Enquire for availability',100)};await database().prepare('INSERT INTO products (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,JSON.stringify(data)).run();return json(data);}
if(path==='admin/projects'){const id=str(body.id||crypto.randomUUID(),100);const title=str(body.title,160);if(!title)throw new Error('Enter a project title.');const data={id,title,category:str(body.category,100),location:str(body.location,200),description:str(body.description),image:imagePath(body.image||''),published:body.published===true};if(data.published&&!data.image)throw new Error('Add a project photo before publishing.');await database().prepare('INSERT INTO projects (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,JSON.stringify(data)).run();return json(data);}
if(path==='admin/settings'){const existing=await settings();const data={...existing,phone:str(body.phone,40),email:str(body.email,160),area:str(body.area,300)};for(const key of ['tiktok','youtube','x','instagram'] as const){if(body[key]===undefined)continue;const value=str(body[key],500);if(value){let url:URL;try{url=new URL(value);}catch{throw new Error('Enter a complete social profile URL.');}const hosts={tiktok:['tiktok.com','www.tiktok.com'],youtube:['youtube.com','www.youtube.com','m.youtube.com'],x:['x.com','www.x.com','twitter.com','www.twitter.com'],instagram:['instagram.com','www.instagram.com']};if(url.protocol!=='https:'||url.username||url.password||!hosts[key].includes(url.hostname)||url.pathname==='/')throw new Error('Use an HTTPS profile link from the matching social platform.');}data[key]=value;}if(data.phone&&!/^\+?[\d ()-]{7,30}$/.test(data.phone))throw new Error('Enter a valid phone number.');if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))throw new Error('Enter a valid email.');await database().prepare("INSERT INTO settings (id,data) VALUES ('business',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind(JSON.stringify(data)).run();return json(data);}
if(path==='admin/status'){if(!['new','contacted','quoted','accepted','deposit-paid','paid','installed','completed','cancelled'].includes(body.status))throw new Error('Invalid status');await database().prepare('UPDATE enquiries SET status=? WHERE id=?').bind(body.status,str(body.id,100)).run();return json({ok:true});}
return json({error:'Not found'},404);
}catch(e){console.error('Finch request failed',e instanceof Error?e.message:'Unknown error');return json({error:e instanceof Error&&!/SQL|D1|R2|database|binding|syntax/i.test(e.message)?e.message:'We could not complete that request. Please try again.'},400);}}

