import type {Product} from './models';
export const cameraBrands=['hikvision','dahua'] as const;
export type CameraBrand=typeof cameraBrands[number];
export const cameraBrandLabel:Record<CameraBrand,string>={hikvision:'Hikvision',dahua:'Dahua'};
export type CctvConfig={brand:CameraBrand;system:'hd'|'ip';cameras:number;channels:4|8|16|32|64;resolution:2|4;audio:boolean;storage:1|2|4;monitor:boolean;backup:boolean;monitorSize:24|32|43|55|65;upsCapacity:600|800|1000|1500|2000;hdmiLength:3|5|10};
export const defaultCctv:CctvConfig={brand:'hikvision',system:'ip',cameras:4,channels:4,resolution:2,audio:false,storage:1,monitor:false,backup:false,monitorSize:24,upsCapacity:600,hdmiLength:3};
export const channelOptions={hd:[4,8,16,32],ip:[4,8,16,32,64]} as const;
export const cameraLimit=(system:CctvConfig['system'])=>system==='hd'?32:64;
export function changeCctvSystem(c:CctvConfig,system:CctvConfig['system']):CctvConfig{return {...c,system,cameras:Math.min(c.cameras,cameraLimit(system)),channels:Math.min(c.channels,cameraLimit(system)) as CctvConfig['channels']};}
export function changeCameraCount(c:CctvConfig,cameras:number):CctvConfig{const channels=(channelOptions[c.system].find(n=>n>=cameras&&n>=c.channels)??cameraLimit(c.system)) as CctvConfig['channels'];return {...c,cameras,channels};}
const part=(id:string,name:string,unit='item',description='Final equipment model and compatibility will be confirmed by Finch.'):Product=>({id:`cctv-${id}`,name,unit,description,category:'CCTV & repairs',price:null,image:'',published:true,availability:'Enquire for availability'});
export const cctvProducts:Product[]=[
...cameraBrands.flatMap(brand=>(['hd','ip'] as const).flatMap(system=>[2,4].flatMap(mp=>[false,true].map(audio=>part(`camera-${brand}-${system}-${mp}-${audio?'audio':'silent'}`,`${cameraBrandLabel[brand]} ${mp}MP ${system==='ip'?'IP':'HD'} camera ${audio?'with audio':'without audio'}`,'camera',`${cameraBrandLabel[brand]} ${system==='ip'?'NVR-based IP':'DVR/XVR-based HD'} camera. ${audio?'Audio requires a compatible recorder and camera.':'Video-only option.'} Exact model to be confirmed.`))))),
...[4,8,16].flatMap(ch=>[part(`nvr-${ch}`,`${ch}-channel PoE NVR`,'recorder','NVR with integrated PoE camera ports. Model, bandwidth, resolution and audio support to be confirmed.'),part(`xvr-${ch}`,`${ch}-channel DVR / XVR`,'recorder','HD recorder. The selected camera format, resolution and audio support must match the final recorder model.')]),
part('xvr-32','32-channel DVR / XVR','recorder','Camera format, resolution, audio support and recording capacity to be confirmed.'),
...[32,64].map(ch=>part(`nvr-${ch}`,`${ch}-channel NVR`,'recorder','External PoE switches included separately. Recorder bandwidth, camera compatibility and storage capacity to be confirmed.')),
part('poe-switch-16','16-port PoE switch with uplink','switch','One switch per up to 16 cameras. PoE power budget, uplink capacity and site topology to be confirmed.'),
part('uplink','Network switch uplink cable','cable','Switch-to-network uplink; type and cable distance to be confirmed on site.'),
...[1,2,4].map(tb=>part(`hdd-${tb}`,`${tb}TB surveillance hard drive`,'drive','Recording duration depends on camera count, resolution, bitrate and recording schedule.')),
part('cat6','CAT6 cable supply','lot','Cable length and final price to be confirmed after measuring the site.'),
part('rg59','RG59 coaxial cable with power','lot','Cable length and final price to be confirmed after measuring the site.'),
part('rj45','RJ45 connector','connector'),part('bnc','BNC connector','connector'),part('dc','DC power connector','connector'),
part('power','CCTV power supply','supply','Power rating and distribution to suit the final camera count and cable distances.'),
part('box','Camera junction box','box'),part('installation','Camera installation & setup','camera','Installation and configuration charge per camera. Site-specific works are quoted separately.'),
...[24,32,43,55,65].map(size=>part(`monitor-${size}`,`${size}-inch viewing monitor / display`,'display','Display model, mounting and recorder output compatibility to be confirmed.')),
...[600,800,1000,1500,2000].map(va=>part(`ups-${va}`,`${va}VA UPS`,'unit','Final suitability depends on connected wattage, power factor and required backup duration. Capacity is not a runtime guarantee.')),
...[3,5,10].map(length=>part(`hdmi-${length}`,`${length}m HDMI cable`,'cable','For the recorder-to-display connection. Required resolution and cable route to be confirmed.')),
part('extension','Power extension strip','strip','For the viewing equipment. Socket count, cable length, plug compatibility and load rating to be confirmed.'),
part('monitor','Viewing monitor','monitor'),part('ups','Recorder backup power / UPS','unit','Size and backup duration to be confirmed against the final connected load.')];
export function cctvSummary(c:CctvConfig){return `${cameraBrandLabel[c.brand]} · ${c.cameras} cameras · ${c.system==='ip'?'IP / NVR':'HD / DVR-XVR'} · ${c.channels} channels · ${c.resolution}MP · ${c.audio?'With audio':'Without audio'} · ${c.storage}TB storage${c.monitor?` · ${c.monitorSize??24}-inch display · ${c.hdmiLength??3}m HDMI + power extension`:``}${c.backup?` · ${c.upsCapacity??600}VA UPS`:``}`;}

export function validateCctv(value:unknown):CctvConfig{if(!value||typeof value!=='object')throw new Error('Choose a CCTV configuration.');const c=value as CctvConfig;if(!(cameraBrands as readonly string[]).includes(c.brand))throw new Error('Choose Hikvision or Dahua before continuing.');if(!['hd','ip'].includes(c.system)||!Number.isInteger(c.cameras)||c.cameras<1||c.cameras>cameraLimit(c.system)||!(channelOptions[c.system] as readonly number[]).includes(c.channels)||c.cameras>c.channels||![2,4].includes(c.resolution)||typeof c.audio!=='boolean'||![1,2,4].includes(c.storage)||typeof c.monitor!=='boolean'||typeof c.backup!=='boolean')throw new Error('Check your CCTV choices. Camera count must fit the recorder capacity.');const monitorSize=c.monitorSize===undefined?24:c.monitorSize;const upsCapacity=c.upsCapacity===undefined?600:c.upsCapacity;const hdmiLength=c.hdmiLength===undefined?3:c.hdmiLength;if(![24,32,43,55,65].includes(monitorSize)||![600,800,1000,1500,2000].includes(upsCapacity)||![3,5,10].includes(hdmiLength))throw new Error('Choose a listed monitor size, UPS capacity and HDMI cable length.');return {brand:c.brand,monitorSize,upsCapacity,hdmiLength,system:c.system,cameras:c.cameras,channels:c.channels,resolution:c.resolution,audio:c.audio,storage:c.storage,monitor:c.monitor,backup:c.backup};}
