export type Offer={id:string;kind:'package'|'maintenance';name:string;description:string;includes:string;price:number|null;frequency:string;route:string;published:boolean};
export const defaultOffers:Offer[]=[
{id:'home-cctv',kind:'package',name:'Home CCTV',description:'Plan camera coverage for your home.',includes:'Camera and recorder selection\nRemote viewing setup\nInstallation proposal after assessment',price:null,frequency:'per installation',route:'/services/cctv',published:true},
{id:'office-network',kind:'package',name:'Office Network Setup',description:'Connect your team with wired and Wi-Fi access.',includes:'Network requirements review\nCabling and Wi-Fi plan\nEquipment and installation quotation',price:null,frequency:'per installation',route:'/services/office-networking',published:true},
{id:'gate-automation',kind:'package',name:'Gate Automation',description:'Plan convenient controlled gate access.',includes:'Gate suitability assessment\nOpener and access-control selection\nInstallation quotation',price:null,frequency:'per installation',route:'/services/automatic-gates',published:true},
{id:'cctv-care',kind:'maintenance',name:'CCTV Care',description:'Scheduled checks for your surveillance system.',includes:'Camera image and recording checks\nStorage and remote viewing checks\nService report; replacement parts quoted separately',price:null,frequency:'Schedule agreed after assessment',route:'/booking?offer=cctv-care',published:true},
{id:'perimeter-care',kind:'maintenance',name:'Fence & Gate Care',description:'Planned maintenance for perimeter security.',includes:'Fence or gate condition checks\nFault assessment\nService report; parts and repairs quoted separately',price:null,frequency:'Schedule agreed after assessment',route:'/booking?offer=perimeter-care',published:true},
{id:'network-care',kind:'maintenance',name:'Office Network Support',description:'Arrange ongoing support for your office.',includes:'Connectivity and Wi-Fi health checks\nTroubleshooting within agreed scope\nService report and recommendations',price:null,frequency:'Schedule agreed after assessment',route:'/booking?offer=network-care',published:true}];
export const defaultCommerceSettings={collection:'Collection location confirmed with your order.',delivery:'Delivery availability, charges and timing are confirmed before payment.',warranty:'Ask for the warranty terms for your selected equipment and installation before accepting a quotation.',returns:'Contact Finch about a return or fault. Applicable terms will be provided with your confirmed quotation.',about:'Finch Networks Ltd provides security, connectivity and automation services for homes and businesses. We install and repair CCTV, electric fences, automatic gates, office networks, Starlink and access control systems.'};
export const salesStatuses=['new','quoted','accepted','deposit-paid','paid','installed','completed','cancelled'];
export const defaultQuoteTerms='Delivery and installation: 4-5 working days, subject to site readiness and material availability.\nQuotation validity: until the date shown on this quotation.\nPayment: the deposit is due on acceptance. The balance is due on completion, testing and commissioning.\nWarranty: equipment follows the manufacturer warranty. Installation workmanship is warranted for 6 months. Warranty excludes physical damage, power surges, misuse, water damage and unauthorised repairs.';
export const defaultQuoteExclusions='Subscriptions, concealed wiring that needs wall cutting, extra electrical works, and any equipment or services not listed in this quotation.';
export const defaultQuotePayment='Cheque payable to Finch Networks Ltd. Finch confirms the M-Pesa details before you pay.';
