export function trackingPath(id:string){return `/track?id=${encodeURIComponent(id)}`;}
export type StaffAlert={kind:'estimate'|'enquiry'|'order'|'visit';reference:string;id:string;name:string;phone:string;location:string;detail?:string};
const staffLabels={estimate:'estimate',enquiry:'enquiry',order:'shop order',visit:'site visit'} as const;
export function staffAlertLabel(kind:StaffAlert['kind']){return staffLabels[kind];}
export function staffAlertText(alert:StaffAlert,origin:string){const detail=(alert.detail||'').trim();return [`New ${staffLabels[alert.kind]} ${alert.reference}`,`${alert.name} · ${alert.phone}`,alert.location,detail,`Open: ${origin}${trackingPath(alert.id)}`,`Admin: ${origin}/admin`].filter(line=>line!=='').join('\n');}
export type CustomerUpdate={kind:'order'|'quote'|'booking'|'enquiry';id:string;status:string;reference?:string;name?:string;customerMessage?:string;date?:string;time?:string;confirmedDate?:string;confirmedTime?:string};
const customerLabels={order:'shop order',quote:'quotation',booking:'site visit',enquiry:'estimate'} as const;
export function customerUpdateLabel(kind:CustomerUpdate['kind']){return customerLabels[kind];}
export function customerUpdateReference(update:CustomerUpdate){if(update.reference)return update.reference;const prefix=update.kind==='booking'?'BOOK':update.kind==='quote'?'QUO':'FN';return `${prefix}-${update.id.slice(0,8).toUpperCase()}`;}
export function customerUpdateText(update:CustomerUpdate,origin:string){const ref=customerUpdateReference(update);const status=String(update.status||'updated').replaceAll('-',' ');const link=update.kind==='quote'?`${origin}/quote?id=${encodeURIComponent(update.id)}`:update.kind==='order'?`${origin}/account/order?id=${encodeURIComponent(update.id)}`:`${origin}${trackingPath(update.id)}`;const visit=update.kind==='booking'&&update.status==='confirmed'?`Visit: ${update.confirmedDate||update.date||'the arranged day'}, ${update.confirmedTime||update.time||'the arranged time'} (Kenya time).`:'';return [`Hello ${update.name||'there'},`,`Your Finch ${customerLabels[update.kind]} ${ref} is now ${status}.`,visit,(update.customerMessage||'').trim(),`View your update: ${link}`,'Keep this link private.'].filter(line=>line!=='').join('\n\n');}
export function whatsappNumber(phone:string){let n=phone.replace(/\D/g,'');if(/^0[17]\d{8}$/.test(n))n='254'+n.slice(1);else if(/^[17]\d{8}$/.test(n))n='254'+n;return n;}
export function notificationText(r:any,origin:string){const ref=r.reference||`${r.kind==='booking'?'BOOK':'FN'}-${r.id.slice(0,8).toUpperCase()}`;const status=String(r.status||'new').replaceAll('-',' ');const parts=[`Hello ${r.name}, this is Finch Networks Ltd.`,`Your ${r.kind==='booking'?'appointment request':r.kind==='quote'?'quotation':'request'} ${ref} is ${status}.`];if(r.kind==='booking'&&r.status==='confirmed')parts.push(`Visit: ${r.confirmedDate||r.date}, ${r.confirmedTime||r.time} (Kenya time).`);if(r.customerMessage)parts.push(r.customerMessage);parts.push(`View your update: ${origin}${r.kind==='quote'?'/quote?id='+encodeURIComponent(r.id):trackingPath(r.id)}`);parts.push('Keep this private link secure. Reply here if you have questions.');return parts.join('\n\n');}
