export const servicePaths=['/services/cctv','/services/electric-fences','/services/automatic-gates','/services/office-networking','/services/starlink'];
export function servicePath(id:string){const n=Number(id.replace('service-',''));return /^service-[0-4]$/.test(id)?servicePaths[n]:null;}
type Field={key:string;label:string;options?:string[];max?:number;unit?:string};
export const planDefinitions={
'electric-fences':{index:1,title:'Plan your electric fence.',description:'Tell us about your perimeter so we can prepare a suitable installation proposal.',fields:[{key:'work',label:'What do you need?',options:['New installation','Repair existing fence','Upgrade existing fence']},{key:'mounting',label:'Fence location',options:['On an existing wall','Freestanding fence','Not sure - advise me']},{key:'length',label:'Approximate perimeter length',max:100000,unit:'metres'},{key:'gates',label:'Number of gates',max:1000,unit:'gates'},{key:'power',label:'Power at the site',options:['Mains power available','Solar required','Not sure - advise me']}]},
'automatic-gates':{index:2,title:'Plan your automatic gate.',description:'Describe your gate and how you want to use it.',fields:[{key:'work',label:'What do you need?',options:['Automate an existing gate','New gate and automation','Repair / replace gate opener']},{key:'style',label:'Gate style',options:['Sliding gate','Swing gate','Not sure - advise me']},{key:'gates',label:'Number of gates',max:100,unit:'gates'},{key:'width',label:'Approximate gate opening',max:100,unit:'metres'},{key:'access',label:'Preferred access',options:['Remote controls','Remote controls and keypad','Remote controls and intercom','Advise me']},{key:'power',label:'Power at the gate',options:['Power available','Power needs to be installed','Not sure']}]},
'office-networking':{index:3,title:'Plan your office network.',description:'Tell us about your office, users and connection needs.',fields:[{key:'work',label:'What do you need?',options:['New office network','Expand an existing network','Repair / troubleshoot']},{key:'connection',label:'Connections required',options:['Wired connections','Wi-Fi','Wired and Wi-Fi']},{key:'users',label:'Approximate number of users',max:100000,unit:'users'},{key:'points',label:'Wired network points',max:10000,unit:'points'},{key:'floors',label:'Number of floors',max:200,unit:'floors'},{key:'internet',label:'Internet connection',options:['Already available','New connection needed','Not sure - advise me']}]},
'starlink':{index:4,title:'Plan your Starlink installation.',description:'Tell us about your equipment and mounting location.',fields:[{key:'equipment',label:'Do you already have a kit?',options:['I need equipment and installation','I have a kit - installation only','Repair / relocate existing installation']},{key:'property',label:'Property type',options:['Home','Office / business','Farm / remote site','Other']},{key:'mount',label:'Preferred mounting location',options:['Roof','Wall / pole','Ground-level location','Not sure - site assessment needed']},{key:'distribution',label:'Connectivity inside the property',options:['Connect to existing network','Wi-Fi setup needed','Network cabling needed','Advise me']}]}
} satisfies Record<string,{index:number;title:string;description:string;fields:Field[]}>;
export type PlanKey=keyof typeof planDefinitions;
export type ServicePlan={service:PlanKey;answers:Record<string,string>;notes:string};
export function validatePlan(value:unknown):ServicePlan{if(!value||typeof value!=='object')throw new Error('Choose a service plan.');const p=value as ServicePlan;if(!Object.hasOwn(planDefinitions,p.service)||!p.answers||typeof p.answers!=='object'||typeof p.notes!=='string'||p.notes.length>2000)throw new Error('Check your service details.');const answers:Record<string,string>={};for(const f of planDefinitions[p.service].fields as Field[]){const v=p.answers[f.key];if(typeof v!=='string'||v.length>150)throw new Error(`Check ${f.label.toLowerCase()}.`);if(f.options&&!f.options.includes(v))throw new Error(`Choose ${f.label.toLowerCase()}.`);if(!f.options&&v!==''&&(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>(f.max||100000)||(f.unit!=='metres'&&!Number.isInteger(Number(v)))))throw new Error(`Enter a valid ${f.label.toLowerCase()}.`);answers[f.key]=v;}return {service:p.service,answers,notes:p.notes.trim()};}
export function planSummary(p:ServicePlan){const d=planDefinitions[p.service];return (d.fields as Field[]).map(f=>`${f.label}: ${p.answers[f.key]||'To be assessed'}${p.answers[f.key]&&f.unit?' '+f.unit:''}`).join('\n')+(p.notes?'\nAdditional details: '+p.notes:'');}
